package com.example.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.net.InetAddress
import kotlin.math.absoluteValue

/**
 * Represents a VPN Profile configuration.
 * 
 * Supports multiple protocols:
 * - VLESS (Reality): Latest anti-censorship protocol with Reality security
 * - Trojan: Protocol designed to evade firewalls
 * - ShadowSocks: Lightweight proxy protocol
 * - VMess: V2Ray's original protocol
 * 
 * @param id Unique profile identifier (auto-generated by Room)
 * @param name Display name for the profile
 * @param serverIp Server IP address (validated as IPv4/IPv6)
 * @param port Server port (1-65535)
 * @param secretKey Secret key/UUID/password depending on protocol
 * @param protocol VPN protocol type
 * @param sni Server Name Indication for TLS fingerprinting
 * @param pbk Public Key for Reality protocol
 * @param sid Short ID for Reality protocol
 * @param fp TLS Fingerprint (chrome, safari, firefox, etc.)
 * @param flow Flow type for VLESS (xtls-rprx-vision, etc.)
 * @param latencyMs Measured latency to server in milliseconds
 * @param isActive Whether this profile is currently active
 */
@Entity(tableName = "vpn_profiles")
data class VpnProfile(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val name: String,
    val serverIp: String,
    val port: Int,
    val secretKey: String,
    val protocol: String = "VLESS (Reality)",
    val sni: String = "www.google.com",
    val pbk: String = "",
    val sid: String = "",
    val fp: String = "chrome",
    val flow: String = "",
    val latencyMs: Int = -1,
    val isActive: Boolean = false
) {
    init {
        validate()
    }

    /**
     * Validates profile configuration
     * @throws IllegalArgumentException if profile is invalid
     */
    private fun validate() {
        // Validate name
        require(name.isNotBlank()) { "Profile name cannot be empty" }
        require(name.length <= 255) { "Profile name is too long (max 255 characters)" }

        // Validate server IP
        require(serverIp.isNotBlank()) { "Server IP cannot be empty" }
        require(isValidIpAddress(serverIp)) { "Invalid IP address: $serverIp" }

        // Validate port
        require(port in 1..65535) { "Port must be between 1 and 65535, got: $port" }

        // Validate secret key based on protocol
        require(secretKey.isNotBlank()) { "Secret key/UUID/password cannot be empty" }
        when {
            protocol.contains("VLESS", ignoreCase = true) -> {
                require(isValidUUID(secretKey)) { "Invalid UUID format for VLESS: $secretKey" }
            }
            protocol.contains("VMess", ignoreCase = true) -> {
                require(isValidUUID(secretKey)) { "Invalid UUID format for VMess: $secretKey" }
            }
        }

        // Validate SNI
        require(sni.isNotBlank()) { "SNI cannot be empty" }
        require(sni.length <= 255) { "SNI is too long" }

        // Validate TLS fingerprint
        require(fp.isNotBlank()) { "TLS Fingerprint cannot be empty" }
        val validFingerprints = setOf("chrome", "firefox", "safari", "edge", "opera")
        require(fp.lowercase() in validFingerprints) { 
            "Invalid fingerprint: $fp. Must be one of: $validFingerprints" 
        }

        // Validate latency
        require(latencyMs >= -1) { "Latency cannot be negative (except -1 for unmeasured)" }
    }

    /**
     * Validates IPv4 or IPv6 address
     */
    private fun isValidIpAddress(ip: String): Boolean {
        return try {
            InetAddress.getByName(ip)
            true
        } catch (e: Exception) {
            false
        }
    }

    /**
     * Validates UUID format (v4)
     */
    private fun isValidUUID(uuid: String): Boolean {
        val uuidRegex = "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$".toRegex(RegexOption.IGNORE_CASE)
        return uuidRegex.matches(uuid) || uuid.length in 32..36 // Allow without hyphens too
    }

    /**
     * Checks if profile has minimal required configuration
     */
    fun isConfigurationComplete(): Boolean {
        return name.isNotBlank() && 
               serverIp.isNotBlank() && 
               port > 0 && 
               secretKey.isNotBlank() &&
               latencyMs >= -1
    }

    /**
     * Returns a safe copy without sensitive information for logging
     */
    fun toSafeString(): String {
        return "VpnProfile(name='$name', ip='${serverIp.maskIp()}', port=$port, protocol='$protocol', latency=${latencyMs}ms)"
    }

    /**
     * Masks IP address for logging (e.g., 1.2.3.4 -> 1.2.3.***)
     */
    private fun String.maskIp(): String {
        val parts = this.split(".")
        return if (parts.size == 4) {
            "${parts[0]}.${parts[1]}.${parts[2]}.***"
        } else {
            "***"
        }
    }
}
